# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true

# Android Gradle Plugin settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Java Home for Gradle Daemon pointing to JDK 21 (JBR 21)
org.gradle.java.home=C:/Users/Talitha/.jdks/jbr-21.0.11

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
